services:
  frontend:
    image: monilight/finrie-front
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    image: monilight/finrie-back
    environment:
      - DATABASE_URL=postgresql://postgres:pass@database:5432/postgres?schema=finrie
      - SECRET=secret
      - CORS_HOSTNAME=localhost
    ports:
      - "5000:5000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      database:
        condition: service_healthy
    links:
      - database
  database:
    container_name: "database"
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
